细化关于sniffing项的作用
v2fly/v2fly-github-io pull request #36
Opened 2020-09-22 12:41 UTC by floatingrain

2020-09-25 01:08 UTC, kslr requested changes
细节应该明确称呼和准确用词
标题不要添加逗号
中英文之间应该有空格

2020-09-25 12:31 UTC, floatingrain commented
> 细节应该明确称呼和准确用词
> 标题不要添加逗号
> 中英文之间应该有空格

已在本pr内进行修改，请查阅

2020-09-27 11:02 UTC, kslr commented
这个描述疏漏很多，我觉得还是不加了吧

2020-09-28 07:53 UTC, floatingrain commented
> 这个描述疏漏很多，我觉得还是不加了吧

是否merge并不重要，如有疏漏，还请指点，想了解自己的缺失。

2020-09-28 07:53 UTC, closed without merging