Update vless.md： Added sample configuration to help users better conf…
v2fly/v2fly-github-io pull request #486
Opened 2024-12-01 04:02 UTC by vxtls

…igure the program.

Added sample configuration to help users better configure the program.

2024-12-04 14:55 UTC, xiaokangwang commented
We already have a repo of configuration examples: https://github.com/v2fly/v2ray-examples/tree/master/v5. Maybe it is better if an example is added to specialized repo and linked here?

2024-12-04 15:48 UTC, vxtls commented
No, I think tutorials like this one are more intuitive: https://www.v2fly.org/guide/start.html, as it provides clear configurations directly, which can help newbies set up quickly.

2024-12-08 21:40 UTC, xiaokangwang commented
I have reassigned review to @AkinoKaede as I was unable to verify if the vless configuration supplied is valid.

2025-03-15 17:23 UTC, AkinoKaede requested changes
This seems to be the configuration of JsonV4

2025-03-15 17:27 UTC, AkinoKaede commented on docs/v5/config/proxy/vless.md
> +        "clients": [
In Simplified Config Format, we define users list like:
```json
"settings": {
    "users": [
        "cc8bdfcd-2d85-4613-9d5e-6c56fcb7a1d3"
    ]
}
```

2025-03-15 17:30 UTC, AkinoKaede commented
> I have reassigned review to @AkinoKaede as I was unable to verify if the vless configuration supplied is valid.

I’ve been swamped with other stuff lately, so I haven’t had a chance to tackle these issues. But LLM has become super popular, so maybe we could use it to write the documentation?

2025-05-22 02:56 UTC, closed without merging