增加dns英文翻译，规范中文文档语句
v2fly/v2fly-github-io pull request #75
Opened 2020-10-12 13:26 UTC by floatingrain

2020-10-12 13:30 UTC, DuckSoft commented on docs/en_US/config/dns.md
> +V2Ray has a built-in DNS server, which has two main purposes: matching routing rules according to the IP which has been resolved from a domain, and traditional DNS function—resolve the target address
```suggestion
V2Ray has a built-in DNS server, which has two main purposes: matching routing rules according to the IP resolved from a domain, and traditional DNS function—resolving the target address to connect.
```

2020-10-12 13:30 UTC, DuckSoft commented on docs/en_US/config/dns.md
> +:::tip Due to the complexity of the DNS protocol, V2Ray only supports the most basic IP query function (A and AAAA records). It is recommended to use local DNS and an additional DNS server for DNS qu
```suggestion
:::tip
Due to the complexity of the DNS protocol, V2Ray only supports the most basic IP query function (A and AAAA records). It is recommended to use local DNS and an additional DNS server for DNS queries, such as [CoreDNS](https://coredns.io/), to use the complete DNS function.
:::
```

2020-10-12 13:31 UTC, DuckSoft commented on docs/en_US/config/dns.md
> +Note: In the `outbound` of the `freedom` protocol, the default value of `domainStrategy` is `AsIs`, and this DNS server will not be used for destination address resolution. If necessary, it should be
Need retranslation here.

2020-10-12 13:57 UTC, floatingrain commented on docs/en_US/config/dns.md
> +Note: In the `outbound` of the `freedom` protocol, the default value of `domainStrategy` is `AsIs`, and this DNS server will not be used for destination address resolution. If necessary, it should be
已更正

2020-10-12 14:41 UTC, nicholascw requested changes

2020-10-12 14:41 UTC, nicholascw commented on docs/en_US/config/dns.md
> +Due to the complexity of DNS protocol, V2Ray only supports basic IP query function (A and AAAA records). It is recommended to use local DNS with an additional DNS server for DNS queries, such as [Cor
```In order to have a complete DNS experience, you may want to use an dedicated DNS serverware, such as [CoreDNS](https://coredns.io), together with V2Ray's builtin DNS features.```

2020-10-12 14:41 UTC, nicholascw commented on docs/en_US/config/dns.md
> +Note: In `outbound` of the `freedom` protocol, the default value of `domainStrategy` is `AsIs`, and this DNS server will not be used for resolving destination address. If necessary, it should be conf
~Note:~ ```For `outbound` with `freedom` protocol, ... . Therefore the DNS settings will not be applied to this outbound by default.```

2020-10-12 20:03 UTC, nicholascw approved these changes

2020-10-13 04:46 UTC, DuckSoft approved these changes

2020-10-13 04:46 UTC, DuckSoft commented on docs/en_US/config/dns.md
> +For `outbound` with `freedom` protocol, the default value of `domainStrategy` is `AsIs`, therefore the DNS settings will not be applied to this outbound by default. If necessary, it should be configu
```suggestion
For `outbound`s with `freedom` protocol, the default value of `domainStrategy` is `AsIs`, therefore the DNS settings will not be applied to this outbound by default. If necessary, it should be configured as`UseIP`.
```

2020-10-13 04:46 UTC, DuckSoft commented on docs/en_US/config/dns.md
> +When a domain name list assigned by a DNS server matches the domain name currently being queried, V2Ray will use this DNS server first, otherwise, it will query from top to bottom, and only return th
第一句话的表述似乎不是很准确。应该是以规则为准吧。

2020-10-13 04:46 UTC, DuckSoft commented on docs/en_US/config/dns.md
> +`DnsObject` corresponds to the `dns` item of the configuration file.
```suggestion
`DnsObject` corresponds to the `dns` field of the configuration file.
```

2020-10-13 04:46 UTC, DuckSoft commented on docs/en_US/config/dns.md
> +Static IP list, its value is a series of "domain name": "address". The address can be an IP or domain name. When resolving a domain name, if the domain name matches an item in this list when the addr
need reorganise.

2020-10-13 04:46 UTC, DuckSoft commented on docs/en_US/config/dns.md
> +A list of DNS servers, supports two types: DNS address (string format) and [ServerObject](#serverobject). When its value is a DNS IP address, such as `"8.8.8.8"`, V2Ray will use port 53 of this addre
```suggestion
A list of DNS servers, supporting two types: DNS address (string format) and [ServerObject](#serverobject). When its value is a DNS IP address, such as `"8.8.8.8"`, V2Ray will use port 53 of this address for DNS query.
```

2020-10-13 04:46 UTC, DuckSoft commented on docs/en_US/config/dns.md
> +When the value is in the form of `"https+local://host:port/dns-query"`, such as `"https+local://dns.google/dns-query"`, V2Ray will use `DOH local mode` for query, that is, DOH requests will not go th
```suggestion
When the value is in the form of `"https+local://host:port/dns-query"`, such as `"https+local://dns.google/dns-query"`, V2Ray will use `DOH local mode` for queries, that is, DOH requests will not go through Routing/Outbound and other components, but directly request externally to improve timing. Generally suitable for use on the server side. Non-standard ports and paths can also be used. (4.22.0+)
```

2020-10-13 04:46 UTC, DuckSoft commented on docs/en_US/config/dns.md
> +> `ExpectIPs`:\[string\]
```suggestion
> `expectIPs`:\[string\]
```

2020-10-13 05:40 UTC, merged